package test.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import test.entity.MerchantStatDayAccess;
import test.entity.MerchantStatDayAccessCriteria;

public interface MerchantStatDayAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    long countByExample(MerchantStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    int deleteByExample(MerchantStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    int insert(MerchantStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    int insertSelective(MerchantStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    List<MerchantStatDayAccess> selectByExampleWithRowbounds(MerchantStatDayAccessCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    List<MerchantStatDayAccess> selectByExample(MerchantStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    List<MerchantStatDayAccess> selectPaginationByExample(MerchantStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    int insertOrUpdateBySelective(MerchantStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    int insert(MerchantStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    int updateByPrimaryKey(MerchantStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    int updateByPrimaryKey(MerchantStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    MerchantStatDayAccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") MerchantStatDayAccess record, @Param("example") MerchantStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    int updateByExample(@Param("record") MerchantStatDayAccess record, @Param("example") MerchantStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Sun Jun 25 23:15:38 CST 2017
     */
    int updateByPrimaryKey(MerchantStatDayAccess record);
}